// Copyright (c) 2026 Beijing Volcano Engine Technology Ltd.

package com.ss.bytertc.engine.flutter;

import com.ss.bytertc.engine.IAudioFrameObserver;
import com.ss.bytertc.engine.IWTNStreamEventHandler;
import com.ss.bytertc.engine.RTCRoomConfig;
import com.ss.bytertc.engine.VideoStreamDescription;
import com.ss.bytertc.engine.data.AudioChannel;
import com.ss.bytertc.engine.data.AudioFrameType;
import com.ss.bytertc.engine.data.AudioSampleRate;
import com.ss.bytertc.engine.data.RemoteMirrorType;
import com.ss.bytertc.engine.data.RemoteVideoConfig;
import com.ss.bytertc.engine.data.StandardPitchInfo;
import com.ss.bytertc.engine.data.StreamInfo;
import com.ss.bytertc.engine.data.VideoRotation;
import com.ss.bytertc.engine.data.WTNSubscribeState;
import com.ss.bytertc.engine.data.WTNSubscribeStateChangeReason;
import com.ss.bytertc.engine.data.ZoomDirectionType;
import com.ss.bytertc.engine.handler.IRTCRoomEventHandler;
import com.ss.bytertc.engine.handler.IRTCEngineEventHandler;
import com.ss.bytertc.engine.SysStats;
import com.ss.bytertc.engine.data.AudioMixingError;
import com.ss.bytertc.engine.data.AudioMixingState;
import com.ss.bytertc.engine.data.AudioPlaybackDevice;
import com.ss.bytertc.engine.data.AudioRoute;
import com.ss.bytertc.engine.data.DataMessageSourceType;
import com.ss.bytertc.engine.data.DeadLockMsg;
import com.ss.bytertc.engine.data.FrameUpdateInfo;
import com.ss.bytertc.engine.data.LocalAudioPropertiesInfo;
import com.ss.bytertc.engine.data.LocalAudioStreamError;
import com.ss.bytertc.engine.data.LocalAudioStreamState;
import com.ss.bytertc.engine.data.MuteState;
import com.ss.bytertc.engine.data.RecordingInfo;
import com.ss.bytertc.engine.data.RecordingProgress;
import com.ss.bytertc.engine.data.RemoteAudioPropertiesInfo;
import com.ss.bytertc.engine.data.RemoteAudioState;
import com.ss.bytertc.engine.data.RemoteAudioStateChangeReason;
import com.ss.bytertc.engine.data.RemoteStreamKey;
import com.ss.bytertc.engine.data.StreamIndex;
import com.ss.bytertc.engine.data.StreamSyncInfoConfig;
import com.ss.bytertc.engine.data.VideoDenoiseMode;
import com.ss.bytertc.engine.data.VideoDenoiseModeChangedReason;
import com.ss.bytertc.engine.type.ChannelProfile;
import com.ss.bytertc.engine.type.ConnectionState;
import com.ss.bytertc.engine.type.RemoteVideoStats;
import com.ss.bytertc.engine.data.VideoFrameInfo;
import com.ss.bytertc.engine.data.VideoSuperResolutionMode;
import com.ss.bytertc.engine.data.VideoSuperResolutionModeChangedReason;
import com.ss.bytertc.engine.live.MixedStreamConfig;
import com.ss.bytertc.engine.live.PushSingleStreamParam;
import com.ss.bytertc.engine.type.AudioDeviceType;
import com.ss.bytertc.engine.type.AudioDumpStatus;
import com.ss.bytertc.engine.type.AudioRecordingErrorCode;
import com.ss.bytertc.engine.type.AudioRecordingState;
import com.ss.bytertc.engine.type.EchoTestResult;
import com.ss.bytertc.engine.type.EffectErrorType;
import com.ss.bytertc.engine.type.FirstFramePlayState;
import com.ss.bytertc.engine.type.FirstFrameSendState;
import com.ss.bytertc.engine.type.HardwareEchoDetectionResult;
import com.ss.bytertc.engine.type.LocalAudioStats;
import com.ss.bytertc.engine.type.LocalProxyError;
import com.ss.bytertc.engine.type.LocalProxyState;
import com.ss.bytertc.engine.type.LocalProxyType;
import com.ss.bytertc.engine.type.LocalVideoStats;
import com.ss.bytertc.engine.type.LocalVideoStreamError;
import com.ss.bytertc.engine.type.LocalVideoStreamState;
import com.ss.bytertc.engine.type.NetworkDetectionLinkType;
import com.ss.bytertc.engine.type.NetworkDetectionStopReason;
import com.ss.bytertc.engine.type.NetworkQuality;
import com.ss.bytertc.engine.type.PerformanceAlarmMode;
import com.ss.bytertc.engine.type.PerformanceAlarmReason;
import com.ss.bytertc.engine.type.PublicStreamErrorCode;
import com.ss.bytertc.engine.type.RecordingErrorCode;
import com.ss.bytertc.engine.type.RecordingState;
import com.ss.bytertc.engine.type.RemoteAudioStats;
import com.ss.bytertc.engine.type.RemoteStreamSwitch;
import com.ss.bytertc.engine.type.RemoteVideoState;
import com.ss.bytertc.engine.type.RemoteVideoStateChangeReason;
import com.ss.bytertc.engine.type.RenderError;
import com.ss.bytertc.engine.type.RtcUser;
import com.ss.bytertc.engine.type.SEIStreamUpdateEvent;
import com.ss.bytertc.engine.type.SourceWantedData;
import com.ss.bytertc.engine.type.VideoDeviceType;
import com.ss.bytertc.engine.utils.IAudioFrame;
import com.ss.bytertc.engine.utils.LogUtil;
import com.ss.bytertc.engine.RTCStream;
import com.ss.bytertc.engine.SubscribeConfig;
import com.ss.bytertc.engine.UserInfo;
import com.ss.bytertc.engine.utils.AudioFrame;
import com.ss.bytertc.engine.data.AVSyncState;
import com.ss.bytertc.engine.data.ForwardStreamEventInfo;
import com.ss.bytertc.engine.data.ForwardStreamStateInfo;
import com.ss.bytertc.engine.type.LocalStreamStats;
import com.ss.bytertc.engine.type.MediaStreamType;
import com.ss.bytertc.engine.type.NetworkQualityStats;
import com.ss.bytertc.engine.type.RTCRoomStats;
import com.ss.bytertc.engine.type.RemoteStreamStats;
import com.ss.bytertc.engine.type.SetRoomExtraInfoResult;
import com.ss.bytertc.engine.type.StreamRemoveReason;
import com.ss.bytertc.engine.type.SubtitleErrorCode;
import com.ss.bytertc.engine.type.SubtitleMessage;
import com.ss.bytertc.engine.type.SubtitleState;
import com.ss.bytertc.engine.type.UserVisibilityChangeError;
import com.ss.bytertc.engine.video.ExpressionDetectInfo;
import com.ss.bytertc.engine.video.ExpressionDetectResult;
import com.ss.bytertc.engine.video.FaceDetectionResult;
import com.ss.bytertc.engine.video.IFaceDetectionObserver;
import com.ss.bytertc.engine.video.ISnapshotResultCallback;
import com.ss.bytertc.engine.video.Rectangle;
import com.ss.bytertc.ktv.IKTVManagerEventHandler;
import com.ss.bytertc.ktv.IKTVPlayerEventHandler;
import com.ss.bytertc.ktv.data.DownloadResult;
import com.ss.bytertc.ktv.data.HotMusicInfo;
import com.ss.bytertc.ktv.data.KTVErrorCode;
import com.ss.bytertc.ktv.data.LyricStatus;
import com.ss.bytertc.ktv.data.MusicInfo;
import com.volcengine.VolcApiEngine.BeanFactory;
import com.volcengine.VolcApiEngine.runtime.Spec;
import com.volcengine.VolcApiEngine.runtime.Util;

import java.lang.reflect.Field;
import java.util.Map;

public class ClassHelper {
  public static void init() {
    BeanFactory.register(IRTCEngineEventHandler.class, ByteRTCVideoEventHandlerImpl.class);
    BeanFactory.register(IRTCRoomEventHandler.class, ByteRTCRoomEventHandlerImpl.class);
    BeanFactory.register(ISnapshotResultCallback.class, ByteRTCSnapShotResultEventHandlerImpl.class);
    BeanFactory.register(IKTVManagerEventHandler.class, ByteRTCKTVManagerEventHandlerImpl.class);
    BeanFactory.register(IKTVPlayerEventHandler.class, ByteRTCKTVPlayerEventHandlerImpl.class);
    BeanFactory.register(IWTNStreamEventHandler.class, ByteRTCWTNEventHandlerImpl.class);
    BeanFactory.register(IFaceDetectionObserver.class, ByteRTCEffectEventHandlerImpl.class);
    BeanFactory.register(IAudioFrameObserver.class, ByteRTCAudioFrameObserverEventProxy.class);

    Util.JsonAbleClass.add(SysStats.class);
    Util.JsonAbleClass.add(StandardPitchInfo.class);
    Util.JsonAbleClass.add(AudioMixingError.class);
    Util.JsonAbleClass.add(AudioMixingState.class);
    Util.JsonAbleClass.add(AudioPlaybackDevice.class);
    Util.JsonAbleClass.add(AudioRoute.class);
    Util.JsonAbleClass.add(DataMessageSourceType.class);
    Util.JsonAbleClass.add(DeadLockMsg.class);
    Util.JsonAbleClass.add(FrameUpdateInfo.class);
    Util.JsonAbleClass.add(LocalAudioPropertiesInfo.class);
    Util.JsonAbleClass.add(LocalAudioStreamError.class);
    Util.JsonAbleClass.add(LocalAudioStreamState.class);
    Util.JsonAbleClass.add(MuteState.class);
    Util.JsonAbleClass.add(RecordingInfo.class);
    Util.JsonAbleClass.add(RecordingProgress.class);
    Util.JsonAbleClass.add(RemoteAudioPropertiesInfo.class);
    Util.JsonAbleClass.add(RemoteAudioState.class);
    Util.JsonAbleClass.add(RemoteAudioStateChangeReason.class);
    Util.JsonAbleClass.add(RemoteStreamKey.class);
    Util.JsonAbleClass.add(StreamIndex.class);
    Util.JsonAbleClass.add(StreamSyncInfoConfig.class);
    Util.JsonAbleClass.add(VideoDenoiseMode.class);
    Util.JsonAbleClass.add(VideoDenoiseModeChangedReason.class);
    Util.JsonAbleClass.add(VideoFrameInfo.class);
    Util.JsonAbleClass.add(VideoSuperResolutionMode.class);
    Util.JsonAbleClass.add(VideoSuperResolutionModeChangedReason.class);
    Util.JsonAbleClass.add(IRTCEngineEventHandler.class);
    Util.JsonAbleClass.add(AudioDeviceType.class);
    Util.JsonAbleClass.add(AudioDumpStatus.class);
    Util.JsonAbleClass.add(AudioRecordingErrorCode.class);
    Util.JsonAbleClass.add(AudioRecordingState.class);
    Util.JsonAbleClass.add(EchoTestResult.class);
    Util.JsonAbleClass.add(EffectErrorType.class);
    Util.JsonAbleClass.add(FirstFramePlayState.class);
    Util.JsonAbleClass.add(FirstFrameSendState.class);
    Util.JsonAbleClass.add(HardwareEchoDetectionResult.class);
    Util.JsonAbleClass.add(LocalProxyError.class);
    Util.JsonAbleClass.add(LocalProxyState.class);
    Util.JsonAbleClass.add(LocalProxyType.class);
    Util.JsonAbleClass.add(LocalVideoStreamError.class);
    Util.JsonAbleClass.add(LocalVideoStreamState.class);
    Util.JsonAbleClass.add(NetworkDetectionLinkType.class);
    Util.JsonAbleClass.add(NetworkDetectionStopReason.class);
    Util.JsonAbleClass.add(PerformanceAlarmMode.class);
    Util.JsonAbleClass.add(PerformanceAlarmReason.class);
    Util.JsonAbleClass.add(PublicStreamErrorCode.class);
    Util.JsonAbleClass.add(RecordingErrorCode.class);
    Util.JsonAbleClass.add(RecordingState.class);
    Util.JsonAbleClass.add(RemoteAudioStats.class);
    Util.JsonAbleClass.add(RemoteStreamSwitch.class);
    Util.JsonAbleClass.add(RemoteVideoState.class);
    Util.JsonAbleClass.add(RemoteVideoStateChangeReason.class);
    Util.JsonAbleClass.add(RenderError.class);
    Util.JsonAbleClass.add(RtcUser.class);
    Util.JsonAbleClass.add(SEIStreamUpdateEvent.class);
    Util.JsonAbleClass.add(SourceWantedData.class);
    Util.JsonAbleClass.add(VideoDeviceType.class);
    Util.JsonAbleClass.add(LogUtil.class);
    Util.JsonAbleClass.add(RTCStream.class);
    Util.JsonAbleClass.add(SubscribeConfig.class);
    Util.JsonAbleClass.add(UserInfo.class);
    Util.JsonAbleClass.add(AVSyncState.class);
    Util.JsonAbleClass.add(ForwardStreamEventInfo.class);
    Util.JsonAbleClass.add(ForwardStreamStateInfo.class);
    Util.JsonAbleClass.add(IRTCRoomEventHandler.class);
    Util.JsonAbleClass.add(LocalStreamStats.class);
    Util.JsonAbleClass.add(MediaStreamType.class);
    Util.JsonAbleClass.add(NetworkQualityStats.class);
    Util.JsonAbleClass.add(RTCRoomStats.class);
    Util.JsonAbleClass.add(RemoteStreamStats.class);
    Util.JsonAbleClass.add(SetRoomExtraInfoResult.class);
    Util.JsonAbleClass.add(StreamRemoveReason.class);
    Util.JsonAbleClass.add(SubtitleErrorCode.class);
    Util.JsonAbleClass.add(SubtitleMessage.class);
    Util.JsonAbleClass.add(SubtitleState.class);
    Util.JsonAbleClass.add(UserVisibilityChangeError.class);
    Util.JsonAbleClass.add(VideoStreamDescription.class);
    Util.JsonAbleClass.add(RemoteVideoState.class);
    Util.JsonAbleClass.add(RemoteAudioState.class);
    Util.JsonAbleClass.add(RemoteVideoStats.class);
    Util.JsonAbleClass.add(LocalAudioStats.class);
    Util.JsonAbleClass.add(LocalVideoStats.class);
    Util.JsonAbleClass.add(NetworkQuality.class);
    Util.JsonAbleClass.add(MusicInfo.class);
    Util.JsonAbleClass.add(HotMusicInfo.class);
    Util.JsonAbleClass.add(VideoRotation.class);
    Util.JsonAbleClass.add(KTVErrorCode.class);
    Util.JsonAbleClass.add(RemoteMirrorType.class);
    Util.JsonAbleClass.add(ZoomDirectionType.class);
    Util.JsonAbleClass.add(RTCRoomConfig.class);
    Util.JsonAbleClass.add(LyricStatus.class);
    Util.JsonAbleClass.add(DownloadResult.class);
    Util.JsonAbleClass.add(ConnectionState.class);
    Util.JsonAbleClass.add(RemoteVideoConfig.class);
    Util.JsonAbleClass.add(ChannelProfile.class);
    Util.JsonAbleClass.add(MixedStreamConfig.class);
    Util.JsonAbleClass.add(PushSingleStreamParam.class);
    Util.JsonAbleClass.add(StreamInfo.class);
    Util.JsonAbleClass.add(WTNSubscribeState.class);
    Util.JsonAbleClass.add(WTNSubscribeStateChangeReason.class);
    Util.JsonAbleClass.add(FaceDetectionResult.class);
    Util.JsonAbleClass.add(ExpressionDetectResult.class);
    Util.JsonAbleClass.add(Rectangle.class);
    Util.JsonAbleClass.add(ExpressionDetectInfo.class);
    Util.JsonAbleClass.add(AudioFrame.class);
    Util.JsonAbleClass.add(IAudioFrame.class);
    Util.JsonAbleClass.add(AudioSampleRate.class);
    Util.JsonAbleClass.add(AudioChannel.class);
    Util.JsonAbleClass.add(AudioFrameType.class);
  }

  public static void merge(Spec.InstanceType instance, Map args) {
    if (instance == null || args == null) {
      return;
    }
    Class<?> clazz = instance.getClass();
    for (Object o : args.entrySet()) {
      Map.Entry entry = (Map.Entry) o;
      Object key = entry.getKey();
      Object value = entry.getValue();
      if (key instanceof String) {
        try {
          Field field = clazz.getDeclaredField((String) key);
          field.setAccessible(true);
          field.set(instance, value);
        } catch (NoSuchFieldException e) {
          // ignore
        } catch (IllegalAccessException e) {
          e.printStackTrace();
        }
      }
    }
  }
}
