name: volc_engine_rtc
description: This Flutter plugin provides rtc sdk native APIs for you to implement
  real-time audio & video communication functions in your application.
version: 3.60.3
homepage: https://www.volcengine.com/docs/6348
author: Volcengine
license: MIT
repository: https://github.com/volcengine/VolcEngineRTC_Flutter_SDK
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'
dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.1
  hybrid_runtime: 0.1.0
dev_dependencies:
  analyzer: ^7.5.9
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.ss.bytertc.engine.flutter
        pluginClass: ByteRTCPlugin
      ios:
        pluginClass: ByteRTCPlugin
env: volc
