import type { AdminRouteDefinition } from 'sdkwork-craw-chat-admin-types';

export const adminRoutes: AdminRouteDefinition[] = [
  {
    key: 'overview',
    label: 'Overview',
    eyebrow: 'Ops',
    detail: 'Message throughput, moderation backlog, and operator shortcuts',
    group: 'Operations',
  },
  {
    key: 'tenants',
    label: 'Tenants',
    eyebrow: 'Workspace',
    detail: 'Tenant posture, organizations, and workspace governance',
    group: 'Workspace Ops',
  },
  {
    key: 'users',
    label: 'Users',
    eyebrow: 'Identity',
    detail: 'Portal identities, operator accounts, and device posture',
    group: 'Workspace Ops',
  },
  {
    key: 'groups',
    label: 'Groups',
    eyebrow: 'Membership',
    detail: 'Group directory, channel governance, and membership posture',
    group: 'Workspace Ops',
  },
  {
    key: 'announcements',
    label: 'Announcements',
    eyebrow: 'Broadcast',
    detail: 'Broadcast tasks, system notices, and delivery posture',
    group: 'Workspace Ops',
  },
  {
    key: 'conversations',
    label: 'Conversations',
    eyebrow: 'Lifecycle',
    detail: 'Conversation lifecycle, handoff, archive, and freeze posture',
    group: 'Conversation Governance',
  },
  {
    key: 'messages',
    label: 'Messages',
    eyebrow: 'Audit',
    detail: 'Message audit, transcript search, export, and evidence review',
    group: 'Conversation Governance',
  },
  {
    key: 'moderation',
    label: 'Moderation',
    eyebrow: 'Safety',
    detail: 'Report queues, keyword policy, and escalation governance',
    group: 'Conversation Governance',
  },
  {
    key: 'automation',
    label: 'Automation',
    eyebrow: 'Bots',
    detail: 'Bot registry, automation runs, and operator workflows',
    group: 'Automation',
  },
  {
    key: 'realtime',
    label: 'Realtime',
    eyebrow: 'Live',
    detail: 'Realtime sessions, RTC posture, and gateway health',
    group: 'System',
  },
  {
    key: 'system',
    label: 'System',
    eyebrow: 'Governance',
    detail: 'Protocol governance, compatibility matrix, and runtime health',
    group: 'System',
  },
  {
    key: 'settings',
    label: 'Settings',
    eyebrow: 'Preferences',
    detail: 'Theme mode, theme color, and sidebar preferences',
    group: 'System',
  },
];
