name: im_sdk_composed
description: Composed Sdkwork IM Flutter SDK with CCP WebSocket realtime.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  im_sdk_generated:
    path: ../../generated/server-openapi
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
